### ISSUE TITLE
Breakwater page links aren't easily detectable as links

### ISSUE THREAD

**Issue by knightlabs** [bdgio/msol-site#101]
See https://mainestateoflearning.org/breakwater – there's three mentions of "The School", of which one is a link; see if you can spot which one.

Options: add an underline, or change the non-hover link color to something easily detectable as a link.

**Comment by kayaelle** [comment]
Made the "The School" link strong. Pushed to develop.

**Comment by kayaelle** [comment]
This is on prod.

**Comment by threeqube** [comment]
Looks and works great. :+1:
