### ISSUE TITLE
On admin panel when you click next page, it keeps going even after page 3 where there's nothing more to load

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#102]
On the following admin panel, click next page:

![screen shot 2015-06-25 at 11 27 36 am](https://cloud.githubusercontent.com/assets/1424627/8362371/44e51d48-1b2d-11e5-8bcb-02449dccc031.png)

You can keep clicking next page and it'll keep going:

![screen shot 2015-06-25 at 11 27 48 am](https://cloud.githubusercontent.com/assets/1424627/8362382/4e349c48-1b2d-11e5-8d53-479d7b385141.png)

**Comment by kayaelle** [comment]
To fix this, I think we'll need to add/change some logic to the pagination code. Worth it?

**Comment by threeqube** [comment]
not worth it until we figure out our plan for msol moving forward so let's put a pin in this for now. Thanks @kayaelle.
