### ISSUE TITLE
[nice-to-have] In badge award emails, make the |BADGE NAME| *bold*

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#103]
Below is the badge award email. 

![screen shot 2015-06-25 at 11 44 02 am](https://cloud.githubusercontent.com/assets/1424627/8362766/a3fb719a-1b2f-11e5-9d5a-03344ccf261d.png)

Badge name gets a bit lost in the text. Make bold to differentiate.

**Comment by kayaelle** [comment]
This is on stage.

**Comment by threeqube** [comment]
Looks great. :+1: to push to prod. 

![screen shot 2015-06-30 at 11 02 27 am](https://cloud.githubusercontent.com/assets/1424627/8437972/aa630106-1f17-11e5-8f4a-d15118124f04.png)

**Comment by threeqube** [comment]
Looks great on prod as well!

<img width="749" alt="screen shot 2015-07-06 at 3 25 17 pm" src="https://cloud.githubusercontent.com/assets/1424627/8534668/4691ae58-23f3-11e5-9215-fde67a42861d.png">
