### ISSUE TITLE
My Badges change edit feature for Name Edit and PW edit buttons are inconsistent

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#105]
In My Badges when you click the pencil icon to edit your name you get the following:

![screen shot 2015-06-25 at 12 21 58 pm](https://cloud.githubusercontent.com/assets/1424627/8363620/f7035d6c-1b34-11e5-955d-9f62f76d3b1b.png)

The buttons say [edit] and [cancel]. 

Meanwhile on the password edit we get the following:

![screen shot 2015-06-25 at 12 22 47 pm](https://cloud.githubusercontent.com/assets/1424627/8363640/0b606afc-1b35-11e5-9289-b20a6b4c9b46.png)

The buttons say [save] and [cancel]. 

I like [save] and [cancel] for both. Can we make them both say that?

**Comment by kayaelle** [comment]
sure. Pushed to develop repo & ready for stage.

**Comment by kayaelle** [comment]
On stage.

**Comment by threeqube** [comment]
Looks good and works great! :+1: to push to prod. 

![screen shot 2015-06-30 at 10 59 09 am](https://cloud.githubusercontent.com/assets/1424627/8437931/3a4a3592-1f17-11e5-8756-8638adb49739.png)

![screen shot 2015-06-30 at 10 59 14 am](https://cloud.githubusercontent.com/assets/1424627/8437932/3a6bc45a-1f17-11e5-9f80-271e4164b426.png)

**Comment by threeqube** [comment]
Looks great on prod as well! :+1:
