### ISSUE TITLE
Create Level Up Page

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#22]
There will likely be 4 - 5 challenges for the pilot. 

![pilot mainstateoflearning org level up page](https://cloud.githubusercontent.com/assets/1424627/7261233/0d23b4e0-e83e-11e4-981f-a144cf0c0633.png)

**Comment by threeqube** [comment]
Level Up page is now going to be super basic. 

For now, text base with the following content: https://docs.google.com/document/d/13f8R8VGGni8QCCVkCab_fRyUVbVYAIbrKOf-wQH_u7c/edit

**Comment by kayaelle** [comment]
Pushed to develop repo. Ready to be deployed to stage. 
Can adults do some of these things? :)

**Comment by threeqube** [comment]
Looks great: https://stage.mainestateoflearning.org/level-up

I think we may want to add some of the challenge badge visuals up top to add some punch to the page but we don't have them yet (currently working with designer to get them designed) so good for now. (Also I can see if I can add this detail later so don't worry @kayaelle.) 

Thanks!

**Comment by threeqube** [comment]
Looks good: https://www.mainestateoflearning.org/level-up

Content will be updated as more orgs submit challenges but we're good to go for now. :+1: 

![screen shot 2015-06-24 at 3 39 54 pm](https://cloud.githubusercontent.com/assets/1424627/8343170/64593b6a-1a87-11e5-9657-23c4981ba4f2.png)
