### ISSUE TITLE
Create Contact Us Form

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#51]

**Comment by threeqube** [comment]
Where did we net out on this? @kayaelle I don't think we're doing this right?

**Comment by kayaelle** [comment]
Yeah we did this. It's the general contact form not the org contact. It's live. Take it for a ride:

https://mainestateoflearning.org/contact-us

**Comment by threeqube** [comment]
That's right! Where do we link to this from?

**Comment by kayaelle** [comment]
In the footer.

**Comment by threeqube** [comment]
Looks great in prod. 

![screen shot 2015-06-24 at 2 09 12 pm](https://cloud.githubusercontent.com/assets/1424627/8341628/f2b0f810-1a7a-11e5-93b3-b298d1c7ec45.png)
