### ISSUE TITLE
After I accept a badge awarded to me, I am unable to click on it to see badge details. 

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#70]
1. I click the link from the badge award email
2. I login to the site
3. I see the new badge in My Badges
![screen shot 2015-06-15 at 3 40 33 pm](https://cloud.githubusercontent.com/assets/1424627/8169085/38a20ea2-1375-11e5-9135-aec970399af5.png)
4. I click accept and add the badge to My Badges
![screen shot 2015-06-15 at 3 40 44 pm](https://cloud.githubusercontent.com/assets/1424627/8169090/41985b10-1375-11e5-9da2-8ac4fd8336dd.png)
5. I click the badge to see the badge details and get the following error:
![screen shot 2015-06-15 at 3 42 20 pm](https://cloud.githubusercontent.com/assets/1424627/8169097/4d0617d0-1375-11e5-9f70-3d720afa72fe.png)

**Comment by kayaelle** [comment]
This page is done and live but the print badge part isn't done yet.

**Comment by threeqube** [comment]
Will test.

**Comment by threeqube** [comment]
This looks and works great. 

![screen shot 2015-06-25 at 12 11 58 pm](https://cloud.githubusercontent.com/assets/1424627/8363391/74c7a34a-1b33-11e5-9b09-ff2fb612b6fa.png)

![screen shot 2015-06-25 at 12 12 06 pm](https://cloud.githubusercontent.com/assets/1424627/8363394/789820e4-1b33-11e5-8668-b915633d623a.png)

And if click the print button voila: 
[InquirythroughChemistryInvestigations_Rachel.pdf](https://github.com/bdgio/msol-site/files/295/InquirythroughChemistryInvestigations_Rachel.pdf)
