### ISSUE TITLE
[nice-to-have] Update About page jumbotron text to be bigger

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#87]
Similar to how we made the jumbotron text on Explore bigger, make the About page jumbotron text to be bigger and wrap text across 2 lines.

**Comment by kayaelle** [comment]
Can do. Where would you like the line break to be?

**Comment by threeqube** [comment]
Feels like it should be as follows:

Find out what Maine State of Learning
has in store for you. 

Thanks!

**Comment by kayaelle** [comment]
Pushed to develop repo. Ready for stage.

**Comment by threeqube** [comment]
Looks great! :+1: 

![screen shot 2015-06-22 at 8 14 13 am](https://cloud.githubusercontent.com/assets/1424627/8285204/b9357f72-18b6-11e5-8fbc-545c8ab7b544.png)

**Comment by threeqube** [comment]
Looks great on prod. :ferris_wheel: 

![screen shot 2015-06-24 at 11 53 22 am](https://cloud.githubusercontent.com/assets/1424627/8338742/ab90c1b2-1a67-11e5-984e-6c2dcdeecd03.png)
