### ISSUE TITLE
Draft Claim page copy

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#95]

**Comment by threeqube** [comment]
Claim page flow:

A [claim your badge] link will be added to the msol header. 
When you click on that you will land on the claim page. 
The Claim page will explain what to do if you got an email or if you have an account. And then what to do if you have a claim code. 

Reference FAQ notes for this.

**Comment by threeqube** [comment]
Claim your badge!

Has your instructor provided you with a claim code to claim your badge? If so, enter it here: [        ]

When you input the claim code, you'll see the badge you just earned along with all its information. You can add your name, print out the badge and share that with your parents, guardians or teachers. 

@kayaelle @megcolek thoughts?

**Comment by megcolek** [comment]
Small suggested tweaks: 

Claim your badge!

Has your instructor provided you with a claim code to get your badge? If so, enter it here: [ ]

After you type in the claim code, you'll see the badge you just earned along with all its information. You can then add your name to your badge and print it so that it’s easy to share it with your friends, parents, guardians or teachers!

**Comment by threeqube** [comment]
I like this :+1: I say :shipit:

**Comment by kayaelle** [comment]
Looks good to me too! Thanks!

1 ques: what should the link in the header be again? "Claim Your Badge"?

**Comment by threeqube** [comment]
Yep I think so. :+1:

**Comment by kayaelle** [comment]
This is on stage.

**Comment by threeqube** [comment]
Looks and works great. :+1: to push to prod. 

![screen shot 2015-06-30 at 11 05 50 am](https://cloud.githubusercontent.com/assets/1424627/8438028/16b81274-1f18-11e5-9841-fc74c6412a55.png)

**Comment by threeqube** [comment]
Looks and works great in prod! :+1: 

<img width="1431" alt="screen shot 2015-07-06 at 3 26 14 pm" src="https://cloud.githubusercontent.com/assets/1424627/8534680/6c2982b2-23f3-11e5-8ace-b2dcbc4b8036.png">
