### ISSUE TITLE
Badge issued to new earner, new earner gets email and clicks on link to set up account and claim: Error received

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#96]
1. Badge is issued to new earner (tried 2 different emails that I also own)
2. Badge award email successfully received in both accounts:

![screen shot 2015-06-24 at 12 01 33 pm](https://cloud.githubusercontent.com/assets/1424627/8338902/ca970bc4-1a68-11e5-8232-22d60f0f8d1d.png)
email link: https://mainestateoflearning.org/claim/npxf-xzgd-3bn4-kq5d

![screen shot 2015-06-24 at 12 02 14 pm](https://cloud.githubusercontent.com/assets/1424627/8338916/e0876082-1a68-11e5-8226-f3ecac12fff8.png)
email link: https://mainestateoflearning.org/claim/iqje-mhbf-ju5v-a6w8

I click on link in both instances and land on the following page:

![screen shot 2015-06-24 at 12 03 26 pm](https://cloud.githubusercontent.com/assets/1424627/8338943/0e230d7a-1a69-11e5-8af1-24ef34572784.png)

![screen shot 2015-06-24 at 12 03 05 pm](https://cloud.githubusercontent.com/assets/1424627/8338947/146185e0-1a69-11e5-887e-c4250efe6070.png)

note urls match.

**Comment by kayaelle** [comment]
My bad. I broke the URL. Will fix shortly.

**Comment by threeqube** [comment]
All good. Thanks!

**Comment by threeqube** [comment]
All fixed! Works great. :tangerine:
