### ISSUE TITLE
urls in badge descriptions are not rendering clickable

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-site#97]
Check out GMRI badge description here: https://www.mainestateoflearning.org/badge/maine-invasive-observer

The urls included are not clickable. Wondering what the level of effort involved to make them hyperlinked. 

Not a critical issue btw.

**Comment by kayaelle** [comment]
Will try making those links html & see if that does it.

**Comment by threeqube** [comment]
Sounds good, no biggie if too much work. Thank you!

**Comment by kayaelle** [comment]
In the description I added html. For example changed:

http://vitalsignsme.org/species-identification-resources

to

<a href="http://vitalsignsme.org/species-identification-resources" target="_blank">http://vitalsignsme.org/species-identification-resources</a>

**Comment by threeqube** [comment]
Cool thank you! Looks great. :tada:
